CREATE TABLE [dbo].[Persons]
(
	[ID] INT PRIMARY KEY IDENTITY,
	[Login] VARCHAR(40) NOT NULL UNIQUE,
	[Password] VARCHAR(500) NOT NULL,
	[Role] SMALLINT NOT NULL,
);

CREATE TABLE [dbo].[CheckRequest]
(
	[ID] INT PRIMARY KEY IDENTITY,
	[HostAddress] VARCHAR(200) NOT NULL,
	[Cron] VARCHAR(100) NOT NULL,
	[PersonID] INT NOT NULL,

	CONSTRAINT FK_CheckRequest_To_Persons FOREIGN KEY (PersonID) REFERENCES [dbo].[Persons] (ID) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TABLE [dbo].[CheckHistory]
(
	[ID] INT PRIMARY KEY IDENTITY,
	[CheckID] INT NOT NULL,
	[Moment] DATETIME NOT NULL,
	[Result] INT NOT NULL,

	CONSTRAINT FK_CheckHistory_To_CheckRequest FOREIGN KEY (CheckID) REFERENCES [dbo].[CheckRequest] (ID) ON DELETE NO ACTION ON UPDATE NO ACTION
);